version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: CouchbaseNetClient
    versions:
    - 3.1.1
    - 3.1.2
    - 3.1.3
  - dependency-name: Unity
    versions:
    - 5.11.9
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
  - dependency-name: CommonServiceLocator
    versions:
    - 2.0.5
